// frontend/src/pages/learner/DeckManagement.jsx
import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { getWorkspaceData } from '../../services/workspaceService';
import { getSavedFlashcards, deleteSavedFlashcardSet } from '../../services/aiService';
import { useConfirm } from '../../contexts/ConfirmContext';
import { useToast } from '../../contexts/ToastContext';

export default function FlashcardDashboard() {
  const navigate = useNavigate();
  const { confirm } = useConfirm();
  const { showToast } = useToast();

  const [decks, setDecks] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [loading, setLoading] = useState(true);

  const fetchDecks = async () => {
    try {
      setLoading(true);
      const ws = await getWorkspaceData();
      const projs = ws?.AI_Project || ws?.AI_Projects || [];
      
      let allDecks = [];
      for (const p of projs) {
        const projId = p.projectId || p.id;
        const res = await getSavedFlashcards(projId).catch(() => ({ data: [] }));
        if (res?.data && Array.isArray(res.data)) {
          res.data.forEach((set, idx) => {
            allDecks.push({
              id: set.flashcardSetId || set.id,
              projectId: projId,
              projectName: p.name || 'Personal Project',
              name: set.title || set.name || `Topic: ${p.name} (Deck ${idx + 1})`,
              cardCount: set.Flashcard?.length || set.cards?.length || set.cardCount || 0,
              archived: p.type === 'CLASS' && (p.status === 'ARCHIVED' || p.courseStatus === 'ARCHIVED')
            });
          });
        }
      }
      setDecks(allDecks);
    } catch (error) {
      console.error('[DeckManagement Error]:', error);
      showToast('Unable to synchronize flashcard deck list.', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDecks();
  }, []);

  const handleDeleteDeck = async (e, projectId, setId, setName) => {
    e.stopPropagation();
    
    const isConfirmed = await confirm({
      title: 'Delete Flashcard Deck',
      message: `Are you sure you want to permanently delete the deck "${setName}"?`,
      confirmLabel: 'Delete Deck',
      cancelLabel: 'Cancel',
      tone: 'danger'
    });

    if (!isConfirmed) return;

    try {
      await deleteSavedFlashcardSet(projectId, setId);
      showToast('Deck deleted successfully!', 'success');
      setDecks(prev => prev.filter(deck => deck.id !== setId));
    } catch (error) {
      showToast('Error deleting deck: ' + error.message, 'error');
    }
  };

  const filteredDecks = decks.filter(deck => 
    deck.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    deck.projectName.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (loading) {
    return (
      <main className="flex-1 flex items-center justify-center p-8 bg-gray-50/50">
        <div className="flex flex-col items-center gap-3">
          <div className="w-8 h-8 rounded-full border-2 border-emerald-600 border-t-transparent animate-spin"></div>
          <p className="text-xs font-bold text-gray-500">Synchronizing Flashcards Library...</p>
        </div>
      </main>
    );
  }

  return (
    <main className="flex-1 p-8 overflow-y-auto space-y-8 bg-gray-50/50">
      {/* HEADER */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-gray-900 tracking-tight">Flashcards Library</h1>
          <p className="text-xs text-gray-500 mt-1 font-medium">
            Synthesize and review flashcard decks generated by AI from your study materials
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="relative">
            <input 
              type="text" 
              placeholder="Search decks, projects..." 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="bg-white border border-gray-200 rounded-2xl pl-9 pr-4 py-2.5 text-xs font-semibold outline-none focus:border-emerald-600 focus:ring-1 focus:ring-emerald-100 transition-all shadow-xs w-64"
            />
            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-xs">🔍</span>
          </div>

          <Link
            to="/learner/ai-workspace"
            className="bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold px-5 py-2.5 rounded-2xl shadow-md shadow-emerald-600/15 hover:shadow-lg transition-all flex items-center gap-2"
          >
            <span>⚡</span> Create more cards in Workspace
          </Link>
        </div>
      </div>

      {/* DECKS GRID */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {filteredDecks.length === 0 ? (
          <div className="col-span-full py-20 text-center bg-white rounded-3xl border border-gray-100 p-8 shadow-xs">
            <div className="w-14 h-14 rounded-2xl bg-emerald-50 text-emerald-600 flex items-center justify-center text-2xl mx-auto mb-3 font-bold">
              🗂️
            </div>
            <h3 className="text-base font-black text-gray-900 mb-1">No flashcard decks available</h3>
            <p className="text-xs text-gray-400 max-w-sm mx-auto mb-6 leading-relaxed">
              {searchTerm 
                ? `No decks found matching "${searchTerm}".`
                : 'Go to AI Workspace, upload lesson materials, and click "Create Flashcards" to let the system automatically draft a deck.'}
            </p>
            <Link
              to="/learner/ai-workspace"
              className="bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold px-6 py-3 rounded-2xl shadow-md transition-all inline-flex items-center gap-2"
            >
              <span>⚡</span> Go to AI Workspace Now
            </Link>
          </div>
        ) : (
          filteredDecks.map(deck => (
            <div 
              key={deck.id} 
              className="bg-white rounded-3xl border border-gray-100 shadow-sm hover:shadow-md transition-all flex flex-col justify-between overflow-hidden group relative"
            >
              {/* Banner */}
              <div className="p-6 bg-gradient-to-br from-emerald-600 via-teal-600 to-emerald-700 text-white flex flex-col justify-between h-36 relative">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-extrabold bg-white/20 backdrop-blur-sm px-2.5 py-1 rounded-full uppercase tracking-wider truncate max-w-[150px]">
                    {deck.projectName}
                  </span>
                  {deck.archived ? (
                    <span className="rounded-full bg-amber-300/90 px-2 py-1 text-[9px] font-black uppercase text-amber-950">Archived</span>
                  ) : (
                    <button
                      type="button"
                      onClick={(e) => handleDeleteDeck(e, deck.projectId, deck.id, deck.name)}
                      className="text-white/60 hover:text-white hover:bg-white/20 p-1.5 rounded-xl text-xs transition-colors"
                      title="Delete deck"
                    >
                      🗑️
                    </button>
                  )}
                </div>
                <div>
                  <h3 className="text-base font-black text-white line-clamp-1 group-hover:text-emerald-100 transition-colors" title={deck.name}>
                    {deck.name}
                  </h3>
                  <p className="text-[11px] text-emerald-100 mt-0.5 font-semibold">
                    Size: {deck.cardCount} flashcards
                  </p>
                </div>
              </div>

              {/* Body */}
              <div className="p-6 flex flex-col justify-between flex-1 gap-4">
                <div className="space-y-2">
                  <div className="flex items-center justify-between text-xs text-gray-500 font-semibold">
                    <span>Deck Status</span>
                    <span className="text-emerald-600 font-bold">Ready for review</span>
                  </div>
                  <div className="w-full bg-gray-100 h-2 rounded-full overflow-hidden">
                    <div className="bg-emerald-500 h-full rounded-full w-full"></div>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={() => navigate(`/learner/flashcards/study?projectId=${deck.projectId}&setId=${deck.id}&name=${encodeURIComponent(deck.name)}`)}
                  className="w-full py-3 rounded-2xl text-xs font-bold text-center bg-emerald-50 hover:bg-emerald-600 text-emerald-700 hover:text-white transition-all shadow-xs block"
                >
                  Start Learning Now →
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </main>
  );
}